# ========== CONFIG ========== #

# You just need to follow the instructions to edit this CONFIG section.

# Dont do anything to this env: word.

env:

  # Everything you need to edit just NAME: and LINK: here to build IPA.

  # Name your app here, it must have the same name in your .xcodeproj, .xcarchive, etc. files.

  NAME: "Goodbye Eternity" # Change this.

  # Enter the direct download link for the compressed .xcodeproj, .xcarchive, etc. files (into a .zip file) here.

  LINK: https://www.dropbox.com/scl/fi/x16r4yq6o0ul3qm1jytpf/Goodbye-Eternity.xcodeproj.zip?rlkey=nljmb4akjj9e65lmajk5p966x&st=kz44521w&dl=1 # Change this.

# That's it, just run this .yml file.





















# You don't need to worry about or edit anything below; just follow the instructions for editing the CONFIG section above.

# ========== BUILD ========== #

name: "Build iOS Unsigned IPA"

on: [push]

jobs:

  build_ios:

    runs-on: macos-14

    steps:

      - name: Checkout repository

        uses: actions/checkout@v4

      - name: Build archive and ipaify

        run: |

          xcodebuild -version

          set -xe

          wget -O archive.zip "${LINK}"

          unzip -o archive.zip -d .

          xcodebuild -list -project "${NAME}.xcodeproj"

          xcodebuild build \
            -project "${NAME}.xcodeproj" \
            -scheme "${NAME}" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_STYLE=Manual
      
          APP_PATH=$(find . -name "*.app" -type d | head -n 1)
      
          mkdir Payload
          cp -r "$APP_PATH" Payload/
      
          zip -r "${NAME}-iOS.ipa" Payload
          mv "${NAME}-iOS.ipa" "${{ runner.temp }}/${NAME}-iOS.ipa"

      - name: Upload application

        uses: actions/upload-artifact@v4

        with:

          name: "${NAME}"

          path: ${{ runner.temp }}/${NAME}-iOS.ipa

          retention-days: 3

# ========== END ========== #
