name: "Build iOS Unsigned iPA"

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build archive and ipaify
        run: |
          echo $FORCE_JAVASCRIPT_ACTIONS_TO_NODE24
          echo $ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION
          node -v
          set -xe
          wget -O archive.zip "https://www.dropbox.com/scl/fi/oqeuzzbgi0j38bbuehw5m/GE.zip?rlkey=3uzbkubjkn24x2api2yie8wvq&st=bsyh0aoj&dl=1"
          unzip -o archive.zip -d .
          xcodebuild -list -project "Goodbye Eternity.xcodeproj"
          xcodebuild archive \
            -project "Goodbye Eternity.xcodeproj" \
            -scheme "Goodbye Eternity" \
            -archivePath "Goodbye Eternity.xcarchive" \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
          mkdir Payload
          mv Goodbye\ Eternity.xcarchive/Products/Applications/*.app Payload/
          zip -r GoodbyeEternity-v0.14.1-iOS.ipa Payload
          mv GoodbyeEternity-v0.14.1-iOS.ipa ${{ runner.temp }}/GoodbyeEternity-v0.14.1-iOS.ipa
      - name: upload application
        uses: actions/upload-artifact@v4
        with:
          name: "GoodbyeEternity"
          path: ${{ runner.temp }}/GoodbyeEternity-v0.14.1-iOS.ipa
          # You can also archive the entire directory
          # Path: ${{ runner.temp }}/build
          retention-days: 3
